// Procedural "photographs": every image in the gallery is painted here, on a
// canvas, so that it is generated by the page itself (same origin, so canvases
// that draw it stay readable) and nothing is downloaded.

export type Ctx = CanvasRenderingContext2D;
export type Painter = (ctx: Ctx, w: number, h: number, rand: () => number) => void;

/** A small, fast seeded random number generator (mulberry32). */
export function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

/** 1D value noise with a few octaves, sampled into an array of `n` values in [-1, 1]. */
function noise1d(n: number, rand: () => number, octaves = 5, base = 6): number[] {
  const out = Array.from({ length: n }, () => 0);
  let amp = 1;
  let total = 0;
  let freq = base;
  for (let o = 0; o < octaves; o++) {
    const knots = Array.from({ length: freq + 2 }, () => rand() * 2 - 1);
    for (let i = 0; i < n; i++) {
      const x = (i / n) * freq;
      const k = Math.floor(x);
      const t = x - k;
      const s = t * t * (3 - 2 * t);
      out[i] += lerp(knots[k], knots[k + 1], s) * amp;
    }
    total += amp;
    amp *= 0.5;
    freq *= 2;
  }
  return out.map((v) => v / total);
}

function linear(
  ctx: Ctx,
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  stops: [number, string][],
) {
  const g = ctx.createLinearGradient(x0, y0, x1, y1);
  for (const [o, c] of stops) g.addColorStop(o, c);
  return g;
}

function radial(ctx: Ctx, x: number, y: number, r: number, stops: [number, string][]) {
  const g = ctx.createRadialGradient(x, y, 0, x, y, r);
  for (const [o, c] of stops) g.addColorStop(o, c);
  return g;
}

/** A mountain ridge: fills below a noisy line. */
function ridge(
  ctx: Ctx,
  w: number,
  h: number,
  rand: () => number,
  base: number,
  amp: number,
  fill: string | CanvasGradient,
  rough = 5,
) {
  const pts = noise1d(200, rand, rough, 3);
  ctx.beginPath();
  ctx.moveTo(0, h);
  for (let i = 0; i < pts.length; i++) ctx.lineTo((i / (pts.length - 1)) * w, base + pts[i] * amp);
  ctx.lineTo(w, h);
  ctx.closePath();
  ctx.fillStyle = fill;
  ctx.fill();
}

function stars(ctx: Ctx, w: number, h: number, rand: () => number, count: number, maxY = 1) {
  for (let i = 0; i < count; i++) {
    const r = rand() ** 3 * 1.8 + 0.3;
    ctx.globalAlpha = 0.3 + rand() * 0.7;
    ctx.fillStyle = "#fff";
    ctx.beginPath();
    ctx.arc(rand() * w, rand() * h * maxY, r, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.globalAlpha = 1;
}

function pine(ctx: Ctx, x: number, baseY: number, height: number, color: string) {
  const width = height * 0.32;
  ctx.fillStyle = color;
  ctx.beginPath();
  const tiers = 5;
  for (let i = 0; i < tiers; i++) {
    const top = baseY - height + (i * height) / tiers / 1.2;
    const bottom = top + height / tiers + height * 0.12;
    const half = (width / 2) * ((i + 1) / tiers);
    ctx.moveTo(x, top);
    ctx.lineTo(x - half, bottom);
    ctx.lineTo(x + half, bottom);
    ctx.closePath();
  }
  ctx.fill();
  ctx.fillRect(x - height * 0.015, baseY - height * 0.08, height * 0.03, height * 0.1);
}

export const painters: Record<string, Painter> = {
  alpine(ctx, w, h, rand) {
    ctx.fillStyle = linear(ctx, 0, 0, 0, h, [
      [0, "#1d2b64"],
      [0.45, "#f8b195"],
      [0.7, "#f67280"],
      [1, "#6c5b7b"],
    ]);
    ctx.fillRect(0, 0, w, h);
    ctx.fillStyle = radial(ctx, w * 0.62, h * 0.48, h * 0.5, [
      [0, "rgba(255,240,200,0.95)"],
      [0.08, "rgba(255,210,160,0.8)"],
      [1, "rgba(255,180,140,0)"],
    ]);
    ctx.fillRect(0, 0, w, h);
    const layers = ["#8e6c88", "#6a4c74", "#4a3561", "#2e2148", "#1a1333"];
    layers.forEach((c, i) => {
      ridge(ctx, w, h, rand, h * (0.45 + i * 0.1), h * (0.18 - i * 0.02), c, 6);
      // Haze between the ridges: a soft gradient, not a hard band.
      const y = h * (0.42 + i * 0.1);
      ctx.fillStyle = linear(ctx, 0, y, 0, y + h * 0.14, [
        [0, "rgba(248,177,149,0)"],
        [0.6, "rgba(248,177,149,0.12)"],
        [1, "rgba(248,177,149,0)"],
      ]);
      ctx.fillRect(0, y, w, h * 0.14);
    });
  },

  dunes(ctx, w, h, rand) {
    ctx.fillStyle = linear(ctx, 0, 0, 0, h * 0.6, [
      [0, "#3a7bd5"],
      [1, "#fbd786"],
    ]);
    ctx.fillRect(0, 0, w, h);
    ctx.fillStyle = radial(ctx, w * 0.25, h * 0.3, h * 0.25, [
      [0, "#fffbe6"],
      [0.25, "rgba(255,243,200,0.9)"],
      [1, "rgba(255,230,160,0)"],
    ]);
    ctx.fillRect(0, 0, w, h);
    const tones = [
      ["#f4a261", "#e76f51"],
      ["#e9a15b", "#c8553d"],
      ["#d68c45", "#9c3d2a"],
      ["#b86b33", "#6e2a1c"],
    ];
    tones.forEach(([light, dark], i) => {
      const y = h * (0.5 + i * 0.13);
      const pts = noise1d(120, rand, 2, 2);
      ctx.beginPath();
      ctx.moveTo(0, h);
      for (let k = 0; k < pts.length; k++)
        ctx.lineTo((k / (pts.length - 1)) * w, y + pts[k] * h * 0.12);
      ctx.lineTo(w, h);
      ctx.closePath();
      ctx.fillStyle = linear(ctx, 0, y - h * 0.1, w * 0.3, y + h * 0.3, [
        [0, light],
        [1, dark],
      ]);
      ctx.fill();
    });
  },

  ocean(ctx, w, h, rand) {
    const horizon = h * 0.55;
    ctx.fillStyle = linear(ctx, 0, 0, 0, horizon, [
      [0, "#0f2027"],
      [0.4, "#2c5364"],
      [0.8, "#ff7e5f"],
      [1, "#feb47b"],
    ]);
    ctx.fillRect(0, 0, w, horizon);
    ctx.fillStyle = radial(ctx, w * 0.5, horizon, h * 0.18, [
      [0, "#fff4d6"],
      [0.35, "#ffd194"],
      [1, "rgba(255,160,100,0)"],
    ]);
    ctx.fillRect(0, 0, w, horizon);
    ctx.fillStyle = linear(ctx, 0, horizon, 0, h, [
      [0, "#b5524a"],
      [0.3, "#203a43"],
      [1, "#0b1418"],
    ]);
    ctx.fillRect(0, horizon, w, h - horizon);
    for (let i = 0; i < 260; i++) {
      const t = rand() ** 1.6;
      const y = horizon + t * (h - horizon);
      const spread = 0.08 + t * 0.5;
      const x = w * 0.5 + (rand() - 0.5) * w * spread;
      const len = (8 + rand() * 50) * (1 + t * 3);
      ctx.fillStyle = `rgba(255,${200 + Math.floor(rand() * 40)},150,${0.6 * (1 - t) + 0.05})`;
      ctx.fillRect(x - len / 2, y, len, 1 + t * 3);
    }
  },

  aurora(ctx, w, h, rand) {
    ctx.fillStyle = linear(ctx, 0, 0, 0, h, [
      [0, "#020617"],
      [0.6, "#0b1d3a"],
      [1, "#0c2d48"],
    ]);
    ctx.fillRect(0, 0, w, h);
    stars(ctx, w, h, rand, 420, 0.7);
    ctx.globalCompositeOperation = "lighter";
    const ribbons = ["rgba(46,255,180,", "rgba(80,200,255,", "rgba(190,90,255,"];
    ribbons.forEach((c, i) => {
      const pts = noise1d(160, rand, 3, 2);
      for (let k = 0; k < pts.length; k++) {
        const x = (k / (pts.length - 1)) * w;
        const y = h * (0.25 + i * 0.08) + pts[k] * h * 0.15;
        const tall = h * (0.15 + 0.2 * Math.abs(pts[(k * 3) % pts.length]));
        ctx.fillStyle = linear(ctx, x, y - tall, x, y + 10, [
          [0, c + "0)"],
          [0.8, c + "0.10)"],
          [1, c + "0.22)"],
        ]);
        ctx.fillRect(x, y - tall, w / pts.length + 1, tall + 10);
      }
    });
    ctx.globalCompositeOperation = "source-over";
    ridge(ctx, w, h, rand, h * 0.78, h * 0.05, "#06121f", 4);
    for (let i = 0; i < 46; i++) {
      const x = rand() * w;
      pine(ctx, x, h * 0.84 + rand() * h * 0.2, h * (0.12 + rand() * 0.18), "#030a12");
    }
  },

  city(ctx, w, h, rand) {
    ctx.fillStyle = linear(ctx, 0, 0, 0, h, [
      [0, "#140b2d"],
      [0.55, "#6b2d6b"],
      [0.85, "#f2709c"],
      [1, "#ff9472"],
    ]);
    ctx.fillRect(0, 0, w, h);
    stars(ctx, w, h, rand, 120, 0.4);
    const layers: [string, number, number][] = [
      ["#3a1d4f", 0.5, 0.75],
      ["#24123a", 0.62, 0.9],
      ["#120821", 0.74, 1.05],
    ];
    for (const [color, top, scale] of layers) {
      let x = -10;
      while (x < w) {
        const bw = (40 + rand() * 90) * scale;
        const bh = h * (0.12 + rand() * 0.38) * scale;
        const y = h * top + h * 0.3 - bh;
        ctx.fillStyle = color;
        ctx.fillRect(x, y, bw, h - y);
        if (scale > 0.8) {
          for (let wy = y + 8; wy < h - 6; wy += 12) {
            for (let wx = x + 6; wx < x + bw - 8; wx += 11) {
              if (rand() < 0.28) {
                ctx.fillStyle = rand() < 0.75 ? "rgba(255,214,120,0.85)" : "rgba(120,220,255,0.8)";
                ctx.fillRect(wx, wy, 5, 6);
              }
            }
          }
        }
        x += bw + rand() * 6;
      }
    }
  },

  forest(ctx, w, h, rand) {
    const water = h * 0.62;
    ctx.fillStyle = linear(ctx, 0, 0, 0, water, [
      [0, "#cfe8e0"],
      [1, "#f6f1d1"],
    ]);
    ctx.fillRect(0, 0, w, water);
    const greens = ["#9db8a0", "#6f9a7f", "#4a7561", "#2b4f43", "#173229"];
    const trees: { x: number; base: number; height: number; color: string }[] = [];
    greens.forEach((g, i) => {
      for (let k = 0; k < 26 + i * 6; k++) {
        trees.push({
          x: rand() * w,
          base: water - (4 - i) * h * 0.02 + rand() * 6,
          height: h * (0.12 + i * 0.05 + rand() * 0.08),
          color: g,
        });
      }
    });
    for (const t of trees) pine(ctx, t.x, t.base, t.height, t.color);
    // Reflection: the top half flipped, faded into the water.
    ctx.save();
    ctx.translate(0, water * 2);
    ctx.scale(1, -1);
    ctx.globalAlpha = 0.55;
    ctx.drawImage(ctx.canvas, 0, 0, w, water, 0, 0, w, water);
    ctx.restore();
    ctx.fillStyle = linear(ctx, 0, water, 0, h, [
      [0, "rgba(64,112,120,0.35)"],
      [1, "rgba(18,40,48,0.9)"],
    ]);
    ctx.fillRect(0, water, w, h - water);
    ctx.fillStyle = "rgba(255,255,255,0.18)";
    for (let i = 0; i < 70; i++)
      ctx.fillRect(rand() * w, water + rand() * (h - water), 20 + rand() * 80, 1);
  },

  meshRose(ctx, w, h, rand) {
    mesh(ctx, w, h, rand, "#ffe3ec", ["#ff6b9d", "#ffa36c", "#c86bfa", "#ffd36b", "#6b8bff"]);
  },

  meshLagoon(ctx, w, h, rand) {
    mesh(ctx, w, h, rand, "#04293a", ["#00c9a7", "#0081cf", "#845ec2", "#4ffbdf", "#2c73d2"]);
  },

  bauhaus(ctx, w, h, rand) {
    ctx.fillStyle = "#efe6d8";
    ctx.fillRect(0, 0, w, h);
    const colors = ["#e63946", "#1d3557", "#f4a261", "#2a9d8f", "#264653", "#e9c46a"];
    const cols = 4;
    const size = w / cols;
    const rows = Math.ceil(h / size);
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        const x = c * size;
        const y = r * size;
        const pick = () => colors[Math.floor(rand() * colors.length)];
        ctx.fillStyle = rand() < 0.4 ? pick() : "#efe6d8";
        ctx.fillRect(x, y, size, size);
        ctx.fillStyle = pick();
        const kind = Math.floor(rand() * 4);
        ctx.save();
        ctx.beginPath();
        ctx.rect(x, y, size, size);
        ctx.clip();
        ctx.beginPath();
        if (kind === 0) ctx.arc(x + size / 2, y + size / 2, size * 0.38, 0, Math.PI * 2);
        else if (kind === 1) {
          const corner = Math.floor(rand() * 4);
          const cx = x + (corner % 2) * size;
          const cy = y + Math.floor(corner / 2) * size;
          ctx.moveTo(cx, cy);
          ctx.arc(cx, cy, size, 0, Math.PI * 2);
        } else if (kind === 2) {
          ctx.moveTo(x, y + size);
          ctx.lineTo(x + size / 2, y);
          ctx.lineTo(x + size, y + size);
        } else ctx.rect(x + size * 0.2, y + size * 0.2, size * 0.6, size * 0.6);
        ctx.fill();
        ctx.restore();
      }
    }
  },

  lowpoly(ctx, w, h, rand) {
    const step = Math.max(w, h) / 12;
    const pts: [number, number][][] = [];
    for (let y = -1; y <= h / step + 1; y++) {
      const row: [number, number][] = [];
      for (let x = -1; x <= w / step + 1; x++)
        row.push([(x + (rand() - 0.5) * 0.8) * step, (y + (rand() - 0.5) * 0.8) * step]);
      pts.push(row);
    }
    const color = (x: number, y: number) => {
      const t = Math.min(1, Math.max(0, (x / w) * 0.6 + (y / h) * 0.4));
      const r = lerp(255, 40, t),
        g = lerp(94, 30, t * t),
        b = lerp(98, 120, t);
      const j = (rand() - 0.5) * 30;
      return `rgb(${(r + j) | 0},${(g + j) | 0},${(b + j) | 0})`;
    };
    for (let y = 0; y < pts.length - 1; y++) {
      for (let x = 0; x < pts[y].length - 1; x++) {
        const a = pts[y][x],
          b = pts[y][x + 1],
          c = pts[y + 1][x],
          d = pts[y + 1][x + 1];
        for (const tri of [
          [a, b, c],
          [b, d, c],
        ]) {
          ctx.beginPath();
          ctx.moveTo(tri[0][0], tri[0][1]);
          ctx.lineTo(tri[1][0], tri[1][1]);
          ctx.lineTo(tri[2][0], tri[2][1]);
          ctx.closePath();
          ctx.fillStyle = color(
            (tri[0][0] + tri[1][0] + tri[2][0]) / 3,
            (tri[0][1] + tri[1][1] + tri[2][1]) / 3,
          );
          ctx.fill();
          ctx.strokeStyle = ctx.fillStyle;
          ctx.stroke();
        }
      }
    }
  },

  waves(ctx, w, h, rand) {
    const colors = ["#023047", "#126782", "#219ebc", "#8ecae6", "#ffb703", "#fb8500"];
    ctx.fillStyle = "#fdf0d5";
    ctx.fillRect(0, 0, w, h);
    const bands = 14;
    for (let i = 0; i < bands; i++) {
      const y = (i / bands) * h * 1.1;
      const amp = h * (0.02 + rand() * 0.04);
      const freq = 1.5 + rand() * 2.5;
      const phase = rand() * Math.PI * 2;
      ctx.beginPath();
      ctx.moveTo(0, h);
      for (let x = 0; x <= w; x += 8)
        ctx.lineTo(x, y + Math.sin((x / w) * Math.PI * 2 * freq + phase) * amp);
      ctx.lineTo(w, h);
      ctx.closePath();
      ctx.fillStyle = colors[i % colors.length];
      ctx.fill();
    }
  },

  rings(ctx, w, h, rand) {
    ctx.fillStyle = "#101418";
    ctx.fillRect(0, 0, w, h);
    const centers = [
      [w * 0.3, h * 0.4],
      [w * 0.72, h * 0.62],
    ];
    const palette = ["#f94144", "#f3722c", "#f8961e", "#f9c74f", "#90be6d", "#43aa8b", "#577590"];
    ctx.globalCompositeOperation = "screen";
    centers.forEach(([cx, cy], k) => {
      for (let r = Math.max(w, h) * 0.6; r > 4; r -= 14 + rand() * 6) {
        ctx.beginPath();
        ctx.arc(cx, cy, r, 0, Math.PI * 2);
        ctx.lineWidth = 5;
        ctx.strokeStyle = palette[(Math.floor(r / 20) + k * 3) % palette.length];
        ctx.globalAlpha = 0.55;
        ctx.stroke();
      }
    });
    ctx.globalAlpha = 1;
    ctx.globalCompositeOperation = "source-over";
  },

  lavender(ctx, w, h, rand) {
    const horizon = h * 0.42;
    ctx.fillStyle = linear(ctx, 0, 0, 0, horizon, [
      [0, "#a1c4fd"],
      [1, "#fde2e4"],
    ]);
    ctx.fillRect(0, 0, w, horizon);
    ridge(ctx, w, h, rand, horizon - h * 0.04, h * 0.05, "#9a8fb5", 4);
    ctx.fillStyle = linear(ctx, 0, horizon, 0, h, [
      [0, "#7b6aa6"],
      [1, "#3c2a63"],
    ]);
    ctx.fillRect(0, horizon, w, h - horizon);
    const vx = w * 0.5;
    const rows = 22;
    for (let i = -rows; i <= rows; i++) {
      ctx.beginPath();
      ctx.moveTo(vx + i * 4, horizon);
      ctx.lineTo(vx + i * w * 0.12, h);
      ctx.lineTo(vx + (i + 0.55) * w * 0.12, h);
      ctx.lineTo(vx + (i + 0.55) * 4, horizon);
      ctx.closePath();
      ctx.fillStyle = linear(ctx, 0, horizon, 0, h, [
        [0, "#b9a7e8"],
        [1, "#9d74e3"],
      ]);
      ctx.fill();
    }
    for (let i = 0; i < 900; i++) {
      const t = rand();
      const y = horizon + t * t * (h - horizon);
      ctx.fillStyle = `rgba(${(200 + rand() * 40) | 0},${(150 + rand() * 50) | 0},255,${0.4 + t * 0.4})`;
      ctx.beginPath();
      ctx.arc(rand() * w, y, 0.5 + t * 3, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.fillStyle = "#3a2f4f";
    const tx = w * 0.78,
      ty = horizon + 6;
    ctx.beginPath();
    ctx.arc(tx, ty - h * 0.07, h * 0.06, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillRect(tx - 3, ty - h * 0.03, 6, h * 0.03);
  },

  moon(ctx, w, h, rand) {
    const horizon = h * 0.66;
    ctx.fillStyle = linear(ctx, 0, 0, 0, horizon, [
      [0, "#0b132b"],
      [1, "#3a506b"],
    ]);
    ctx.fillRect(0, 0, w, horizon);
    stars(ctx, w, horizon, rand, 260);
    const mx = w * 0.7,
      my = h * 0.26,
      mr = Math.min(w, h) * 0.1;
    ctx.fillStyle = radial(ctx, mx, my, mr * 4, [
      [0, "rgba(255,250,230,0.45)"],
      [1, "rgba(255,250,230,0)"],
    ]);
    ctx.fillRect(0, 0, w, horizon);
    ctx.fillStyle = "#fdf6e3";
    ctx.beginPath();
    ctx.arc(mx, my, mr, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = "rgba(200,190,170,0.35)";
    for (let i = 0; i < 7; i++) {
      ctx.beginPath();
      ctx.arc(
        mx + (rand() - 0.5) * mr * 1.2,
        my + (rand() - 0.5) * mr * 1.2,
        mr * (0.08 + rand() * 0.15),
        0,
        Math.PI * 2,
      );
      ctx.fill();
    }
    ridge(ctx, w, h, rand, horizon - h * 0.03, h * 0.04, "#1c2541", 5);
    ctx.fillStyle = linear(ctx, 0, horizon, 0, h, [
      [0, "#1c2541"],
      [1, "#05070f"],
    ]);
    ctx.fillRect(0, horizon, w, h - horizon);
    for (let i = 0; i < 90; i++) {
      const t = rand();
      const y = horizon + t * (h - horizon);
      const len = 10 + rand() * 60 * (1 + t);
      ctx.fillStyle = `rgba(253,246,227,${0.7 * (1 - t)})`;
      ctx.fillRect(mx - len / 2 + (rand() - 0.5) * mr * (1 + t * 2), y, len, 1.5);
    }
  },

  contour(ctx, w, h, rand) {
    const img = ctx.createImageData(w, h);
    const gx = 7,
      gy = Math.round((7 * h) / w);
    const grid = Array.from({ length: (gx + 2) * (gy + 2) }, () => rand());
    const at = (x: number, y: number) => grid[y * (gx + 2) + x];
    const field = (u: number, v: number) => {
      const x = u * gx,
        y = v * gy;
      const ix = Math.floor(x),
        iy = Math.floor(y);
      const fx = x - ix,
        fy = y - iy;
      const sx = fx * fx * (3 - 2 * fx),
        sy = fy * fy * (3 - 2 * fy);
      return lerp(
        lerp(at(ix, iy), at(ix + 1, iy), sx),
        lerp(at(ix, iy + 1), at(ix + 1, iy + 1), sx),
        sy,
      );
    };
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const v = field(x / w, y / h) * 0.8 + field(((x / w) * 3) % 1, ((y / h) * 3) % 1) * 0.05;
        const bands = v * 18;
        const line = Math.abs(bands - Math.round(bands)) < 0.05;
        const i = (y * w + x) * 4;
        const t = v;
        img.data[i] = line ? 250 : lerp(18, 40, t);
        img.data[i + 1] = line ? 200 : lerp(40, 90, t);
        img.data[i + 2] = line ? 120 : lerp(60, 110, t);
        img.data[i + 3] = 255;
      }
    }
    ctx.putImageData(img, 0, 0);
  },

  prism(ctx, w, h, rand) {
    ctx.fillStyle = "#0d0d12";
    ctx.fillRect(0, 0, w, h);
    const ox = w * 0.18,
      oy = h * 0.5;
    const hues = [0, 30, 55, 120, 200, 260, 300];
    ctx.globalCompositeOperation = "lighter";
    hues.forEach((hue, i) => {
      const angle = -0.35 + i * 0.11 + (rand() - 0.5) * 0.02;
      const g = ctx.createLinearGradient(
        ox,
        oy,
        ox + Math.cos(angle) * w,
        oy + Math.sin(angle) * w,
      );
      g.addColorStop(0, `hsla(${hue},95%,60%,0.9)`);
      g.addColorStop(1, `hsla(${hue},95%,50%,0)`);
      ctx.fillStyle = g;
      ctx.beginPath();
      ctx.moveTo(ox, oy);
      ctx.lineTo(ox + Math.cos(angle - 0.05) * w * 1.2, oy + Math.sin(angle - 0.05) * w * 1.2);
      ctx.lineTo(ox + Math.cos(angle + 0.05) * w * 1.2, oy + Math.sin(angle + 0.05) * w * 1.2);
      ctx.closePath();
      ctx.fill();
    });
    ctx.globalCompositeOperation = "source-over";
    ctx.fillStyle = "rgba(255,255,255,0.85)";
    ctx.beginPath();
    ctx.moveTo(0, oy + 3);
    ctx.lineTo(ox, oy);
    ctx.lineTo(0, oy - 3);
    ctx.fill();
    ctx.strokeStyle = "rgba(220,230,255,0.7)";
    ctx.lineWidth = 3;
    ctx.fillStyle = "rgba(160,180,220,0.12)";
    ctx.beginPath();
    ctx.moveTo(ox - h * 0.12, oy + h * 0.14);
    ctx.lineTo(ox + h * 0.02, oy - h * 0.2);
    ctx.lineTo(ox + h * 0.16, oy + h * 0.14);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
  },

  terrazzo(ctx, w, h, rand) {
    ctx.fillStyle = "#f3ede4";
    ctx.fillRect(0, 0, w, h);
    const colors = ["#d97b66", "#3d5a80", "#98c1d9", "#ee6c4d", "#293241", "#e0c097", "#8a9a5b"];
    for (let i = 0; i < 520; i++) {
      const x = rand() * w,
        y = rand() * h;
      const r = 4 + rand() ** 2.5 * 40;
      const sides = 3 + Math.floor(rand() * 4);
      const rot = rand() * Math.PI;
      ctx.beginPath();
      for (let s = 0; s < sides; s++) {
        const a = rot + (s / sides) * Math.PI * 2;
        const rr = r * (0.6 + rand() * 0.5);
        ctx.lineTo(x + Math.cos(a) * rr, y + Math.sin(a) * rr);
      }
      ctx.closePath();
      ctx.fillStyle = colors[Math.floor(rand() * colors.length)];
      ctx.fill();
    }
  },

  canyon(ctx, w, h, rand) {
    ctx.fillStyle = linear(ctx, 0, 0, 0, h * 0.5, [
      [0, "#89c2d9"],
      [1, "#f9dcc4"],
    ]);
    ctx.fillRect(0, 0, w, h);
    const strata = ["#d4a373", "#c97c5d", "#b56545", "#9a4f36", "#7f3b2a", "#5e2a20"];
    for (let i = 0; i < strata.length; i++) {
      const left = noise1d(80, rand, 3, 2);
      const y0 = h * (0.25 + i * 0.12);
      ctx.beginPath();
      ctx.moveTo(0, h);
      for (let k = 0; k < left.length; k++) {
        const x = (k / (left.length - 1)) * w;
        const cliff = Math.abs(x - w * 0.5) < w * (0.08 + i * 0.03) ? h * 0.08 : 0;
        ctx.lineTo(x, y0 + left[k] * h * 0.03 + cliff);
      }
      ctx.lineTo(w, h);
      ctx.closePath();
      ctx.fillStyle = strata[i];
      ctx.fill();
      ctx.fillStyle = "rgba(255,230,200,0.08)";
      for (let s = 0; s < 6; s++) ctx.fillRect(0, y0 + s * 9 + 10, w, 2);
    }
  },
};

function mesh(ctx: Ctx, w: number, h: number, rand: () => number, bg: string, colors: string[]) {
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, w, h);
  for (let i = 0; i < 9; i++) {
    const c = colors[i % colors.length];
    const x = rand() * w,
      y = rand() * h,
      r = Math.max(w, h) * (0.3 + rand() * 0.4);
    ctx.fillStyle = radial(ctx, x, y, r, [
      [0, c],
      [1, c + "00"],
    ]);
    ctx.globalAlpha = 0.75;
    ctx.fillRect(0, 0, w, h);
  }
  ctx.globalAlpha = 1;
}

let grain: HTMLCanvasElement | null = null;

/** A light film grain over the whole image, so that gradients don't band and look photographic. */
export function addGrain(ctx: Ctx, w: number, h: number, amount = 0.07) {
  if (!grain) {
    grain = document.createElement("canvas");
    grain.width = grain.height = 160;
    const g = grain.getContext("2d")!;
    const data = g.createImageData(160, 160);
    const rand = rng(7);
    for (let i = 0; i < data.data.length; i += 4) {
      const v = (rand() * 255) | 0;
      data.data[i] = data.data[i + 1] = data.data[i + 2] = v;
      data.data[i + 3] = 255;
    }
    g.putImageData(data, 0, 0);
  }
  ctx.save();
  ctx.globalAlpha = amount;
  ctx.globalCompositeOperation = "overlay";
  ctx.fillStyle = ctx.createPattern(grain, "repeat")!;
  ctx.fillRect(0, 0, w, h);
  ctx.restore();
}
